type = "webpack"
zone_id = "31dea2e3e5ae934dd42318d435be55c7"
account_id = "8f8eea48fc5a7f0009e0e5569fcced9c"
route = "https://kylepetrovi.ch/dota*"
workers_dev = true
webpack_config = "webpack.config.js"
name = "dota-match-bot"
kv_namespaces = [
  { binding = "PLAYERS", id = "378d095572724a6db9810bfe810d524f" },
  { binding = "GUILDS", id = "bc290482eeb14698a9efd1e490f9a287" }
]